Add synonym: Royal Holloway University of London
DFE-Digital/dfe-reference-data pull request #4
Opened 2022-05-19 08:10 UTC by frankieroberto

This should match even if the comma is missing - 2 candidates have entered it this way.

2022-05-19 09:46 UTC, edwardhorsford commented
I'm not sure this should be needed? A service could match with and without punctuation - otherwise should we add match synonyms to all other items that have commas?

2022-05-19 10:52 UTC, frankieroberto commented
> I'm not sure this should be needed? A service could match with and without punctuation - otherwise should we add match synonyms to all other items that have commas?

Possibly not, but doesn't do any harm? And useful for any services who might forget to strip punctuation when matching...

2022-05-19 17:33 UTC, edwardhorsford commented
To play devil's advocate - why just this entry then? there's lots of University of Londons in the list.

2022-05-20 12:53 UTC, frankieroberto commented
> To play devil's advocate - why just this entry then? there's lots of University of Londons in the list.

Fair point. This is the only one that has come up so far in actual usage so far though. But we should perhaps also update our code in Apply to ignore punctuation (just commas?) when matching.

2022-06-22 09:49 UTC, alaric-dfe requested changes
Yeah, I reckon this is more of an issue of the code needing to be a bit fuzzier in matching. Otherwise we'll end up with a load of boring synonyms on every entry, and the amount of "fuzz" added in the synonyms will be inconsistent between entries (based on which ones have been a pain for us in the past), leading to an inconsistent and confusing UX.

2022-06-23 08:46 UTC, closed without merging